spring:
  application:
    name: blog
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: debug